config/routes.rb
Rails.application.routes.draw do
  root 'plaques#index'

  resources :plaques do
    collection do
      get 'can_circulate'
    end
  end

end

app/models/plaque.rb
class Plaque < ActiveRecord::Base

  def initialize
  end

  class << self
    def can_circulate?(full_number, full_date)
      # Get times parameters
      get_times(full_date)
      # Number day of weekend
      day = DateTime.parse(full_date).wday
      # Last number for cars
      last_number = full_number.last(1)
      # Last number for motorcycles
      unless /^[0-9]+$/.match(last_number)
        last_number = full_number.last(2).first
      end
      # Last number to interger
      last_number = last_number.to_i
      # Can circulate on the road
      if @full_date.between?(@morning_from, @morning_to) || @full_date.between?(@afternoon_from, @afternoon_to)
        # weekdays
        if day == 1 && (last_number == 1 || last_number == 2)
          can_circulate = false
        elsif day == 2 && (last_number == 3 || last_number == 4)
          can_circulate = false
        elsif day == 3 && (last_number == 5 || last_number == 6)
          can_circulate = false
        elsif day == 4 && (last_number == 7 || last_number == 8)
          can_circulate = false
        elsif day == 5 && (last_number == 9 || last_number == 0)
          can_circulate = false
        # weekend
        elsif day == 6 || day == 0
          can_circulate = true
        end
      else
        can_circulate = true
      end
      return can_circulate
    end     


    def valid_plaque?(plaque)
      /[a-z]{3}[0-9]{4}/.match(plaque.downcase) || /[a-z]{2}[0-9]{3}[a-z]{1}/.match(plaque.downcase) ? true : false   
    end

    def valid_date?(date)
      DateTime.parse date rescue false
    end

    def get_times(full_date)
      @full_date = Time.parse(full_date)
      @morning_from = Time.parse("07:00:00")
      @morning_to = Time.parse("09:30:00")
      @afternoon_from = Time.parse("16:00:00")
      @afternoon_to = Time.parse("19:30:00")
    end


  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plaques_controller.rb
class PlaquesController < ApplicationController
  # before_action :set_plaque, only: [:show, :edit, :update, :destroy]

  # GET /plaques
  # GET /plaques.json
  def index
    @date = params[:date] || Time.now.to_s(:db)
  end

  def can_circulate
    full_number = params[:number]
    full_date = params[:date]

    Rails.logger.info ""
    pa = Plaque.new
    if Plaque.valid_plaque?(full_number) && Plaque.valid_date?(full_date)
      can_circulate = Plaque.can_circulate?(full_number, full_date)
      msj = can_circulate ? "Can circulate on the road" : "Can not circulate on the road"
    else
      msj = "Invalid data"
    end
    respond_to do |format|
      format.html { redirect_to plaques_url(:number => params[:number], :date => params[:date]), notice: msj }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plaques_helper.rb
module PlaquesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picoplaca</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plaques/_form.html.erb
<%= form_for(@plaque) do |f| %>
  <% if @plaque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plaque.errors.count, "error") %> prohibited this plaque from being saved:</h2>

      <ul>
      <% @plaque.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plaques/edit.html.erb
<h1>Editing Plaque</h1>

<%= render 'form' %>

<%= link_to 'Show', @plaque %> |
<%= link_to 'Back', plaques_path %>

app/views/plaques/index.html.erb
<%if notice%>
  <p id="notice"><%= notice %></p>
<%end%>


<h1>"Pico y placa" predictor</h1>

<%= form_tag('/plaques/can_circulate', :method => 'get') do |f| %>
  <div class="field">
    <%= label_tag :number, "Plaque" %><br>
    <%= text_field_tag :number, params[:number] %>
  </div>

  <div class="field">
    <%= label_tag :date, "Date (ex. 2011-05-19 10:30:14)" %><br>
    <%= text_field_tag :date, @date %>
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/plaques/new.html.erb
<h1>New Plaque</h1>

<%= render 'form' %>

<%= link_to 'Back', plaques_path %>

app/views/plaques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @plaque.number %>
</p>

<%= link_to 'Edit', edit_plaque_path(@plaque) %> |
<%= link_to 'Back', plaques_path %>